/**
 * Prisma seed — Source Population Phase
 *
 * Creates all curated Source records (status: approved) and SourceLink records
 * linking them to their respective graph nodes.
 *
 * Run with: npx tsx prisma/seed.ts
 *   or via:  npm run db:seed
 */
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// ---------------------------------------------------------------------------
// Source definitions (mirrors lib/graph/sources.ts but with DB-required fields)
// ---------------------------------------------------------------------------

interface SeedSource {
  slug: string;             // stable key for upsert / SourceLink linkage
  title: string;
  sourceType: string;
  author?: string;
  publicationYear?: number;
  publisher?: string;
  journal?: string;
  url?: string;
  doi?: string;
  abstract?: string;
  credibilityScore: number;
  notes?: string;
  nodeIds: string[];        // which graph nodes to link
  linkType?: 'supports' | 'contradicts' | 'references';
}

const SOURCES: SeedSource[] = [

  // ── GÖBEKLI TEPE ─────────────────────────────────────────────────────────

  {
    slug: 'schmidt-2010-gobekli',
    title: 'Göbekli Tepe – the Stone Age Sanctuaries: New Results of Ongoing Excavations with a Special Focus on Sculptures and High Reliefs',
    sourceType: 'Academic Paper',
    author: 'Klaus Schmidt',
    publicationYear: 2010,
    journal: 'Documenta Praehistorica',
    url: 'https://doi.org/10.4312/dp.37.21',
    credibilityScore: 0.92,
    notes: 'The primary excavator\'s definitive account of the site.',
    nodeIds: ['gobekli-tepe'],
    linkType: 'supports',
  },
  {
    slug: 'dietrich-2012-gobekli-feasting',
    title: 'The role of cult and feasting in the emergence of Neolithic communities: New evidence from Göbekli Tepe, south-eastern Turkey',
    sourceType: 'Academic Paper',
    author: 'Oliver Dietrich, Manfred Heun, Jens Notroff, Klaus Schmidt, Martin Zarnkow',
    publicationYear: 2012,
    journal: 'Antiquity',
    credibilityScore: 0.90,
    notes: 'Addresses feasting and social complexity preceding agriculture.',
    nodeIds: ['gobekli-tepe'],
    linkType: 'supports',
  },
  {
    slug: 'schmidt-2006-gobekli-book',
    title: 'Sie bauten die ersten Tempel (They Built the First Temples)',
    sourceType: 'Book',
    author: 'Klaus Schmidt',
    publicationYear: 2006,
    publisher: 'Beck Verlag',
    credibilityScore: 0.90,
    notes: 'Schmidt\'s own synthesis of the Göbekli Tepe excavations.',
    nodeIds: ['gobekli-tepe', 'ancient-megalithic-sites'],
    linkType: 'supports',
  },
  {
    slug: 'peters-schmidt-2004-animals',
    title: 'Animals in the symbolic world of Pre-Pottery Neolithic Göbekli Tepe, south-eastern Turkey: a preliminary assessment',
    sourceType: 'Academic Paper',
    author: 'Joris Peters, Klaus Schmidt',
    publicationYear: 2004,
    journal: 'Anthropozoologica',
    credibilityScore: 0.88,
    notes: 'Detailed analysis of the carved animal reliefs.',
    nodeIds: ['gobekli-tepe'],
    linkType: 'supports',
  },

  // ── ATLANTIS ──────────────────────────────────────────────────────────────

  {
    slug: 'plato-timaeus',
    title: 'Timaeus',
    sourceType: 'Historical Text',
    author: 'Plato',
    publicationYear: -360,
    credibilityScore: 0.95,
    notes: 'Primary source. First appearance of the Atlantis narrative, c. 360 BCE.',
    nodeIds: ['atlantis', 'comparative-mythology'],
    linkType: 'references',
  },
  {
    slug: 'plato-critias',
    title: 'Critias',
    sourceType: 'Historical Text',
    author: 'Plato',
    publicationYear: -360,
    credibilityScore: 0.95,
    notes: 'Companion dialogue with more geographic detail on Atlantis.',
    nodeIds: ['atlantis'],
    linkType: 'references',
  },
  {
    slug: 'vidal-naquet-2007-atlantis',
    title: 'The Atlantis Story: A Short History of Plato\'s Myth',
    sourceType: 'Book',
    author: 'Pierre Vidal-Naquet',
    publicationYear: 2007,
    publisher: 'University of Exeter Press',
    credibilityScore: 0.88,
    notes: 'Leading classical scholar\'s comprehensive argument for the literary allegory interpretation.',
    nodeIds: ['atlantis', 'comparative-mythology'],
    linkType: 'contradicts',
  },
  {
    slug: 'gill-1977-atlantis-origin',
    title: 'The Origin of the Atlantis Myth',
    sourceType: 'Academic Paper',
    author: 'Christopher Gill',
    publicationYear: 1977,
    journal: 'Trivium',
    credibilityScore: 0.88,
    notes: 'Argues Plato invented Atlantis as a philosophical device.',
    nodeIds: ['atlantis'],
    linkType: 'contradicts',
  },
  {
    slug: 'castleden-1998-atlantis-destroyed',
    title: 'Atlantis Destroyed',
    sourceType: 'Book',
    author: 'Rodney Castleden',
    publicationYear: 1998,
    publisher: 'Routledge',
    credibilityScore: 0.62,
    notes: 'Proposes Minoan Thera eruption as historical basis. Minority academic position.',
    nodeIds: ['atlantis', 'flood-narratives'],
    linkType: 'supports',
  },

  // ── SUMERIAN CIVILIZATION ─────────────────────────────────────────────────

  {
    slug: 'kramer-1963-sumerians',
    title: 'The Sumerians: Their History, Culture, and Character',
    sourceType: 'Book',
    author: 'Samuel Noah Kramer',
    publicationYear: 1963,
    publisher: 'University of Chicago Press',
    credibilityScore: 0.92,
    notes: 'Foundational scholarly synthesis by the leading Sumerologist of the 20th century.',
    nodeIds: ['sumerian-civilization', 'epic-of-gilgamesh'],
    linkType: 'supports',
  },
  {
    slug: 'postgate-1992-mesopotamia',
    title: 'Early Mesopotamia: Society and Economy at the Dawn of History',
    sourceType: 'Book',
    author: 'J.N. Postgate',
    publicationYear: 1992,
    publisher: 'Routledge',
    credibilityScore: 0.92,
    notes: 'Standard academic reference for Sumerian economic and social organization.',
    nodeIds: ['sumerian-civilization'],
    linkType: 'supports',
  },
  {
    slug: 'etcsl-2006',
    title: 'The Electronic Text Corpus of Sumerian Literature (ETCSL)',
    sourceType: 'Historical Text',
    author: 'J.A. Black, G. Cunningham, J. Ebeling et al.',
    publicationYear: 2006,
    url: 'https://etcsl.orinst.ox.ac.uk/',
    credibilityScore: 0.95,
    notes: 'Oxford University. Comprehensive transliteration and translation of Sumerian literary texts.',
    nodeIds: ['sumerian-civilization', 'epic-of-gilgamesh', 'flood-narratives'],
    linkType: 'references',
  },
  {
    slug: 'nissen-1988-early-mesopotamia',
    title: 'The Early History of the Ancient Near East, 9000–2000 B.C.',
    sourceType: 'Book',
    author: 'Hans J. Nissen',
    publicationYear: 1988,
    publisher: 'University of Chicago Press',
    credibilityScore: 0.90,
    notes: 'Definitive account of Mesopotamian development from pre-ceramic Neolithic through Early Dynastic.',
    nodeIds: ['sumerian-civilization'],
    linkType: 'supports',
  },

  // ── INDUS VALLEY ─────────────────────────────────────────────────────────

  {
    slug: 'kenoyer-1998-indus',
    title: 'Ancient Cities of the Indus Valley Civilization',
    sourceType: 'Book',
    author: 'Jonathan Mark Kenoyer',
    publicationYear: 1998,
    publisher: 'Oxford University Press',
    credibilityScore: 0.93,
    notes: 'Standard scholarly reference on Harappan urban archaeology.',
    nodeIds: ['indus-valley'],
    linkType: 'supports',
  },
  {
    slug: 'possehl-2002-indus',
    title: 'The Indus Civilization: A Contemporary Perspective',
    sourceType: 'Book',
    author: 'Gregory L. Possehl',
    publicationYear: 2002,
    publisher: 'AltaMira Press',
    credibilityScore: 0.92,
    notes: 'Comprehensive synthesis of Indus Valley research.',
    nodeIds: ['indus-valley'],
    linkType: 'supports',
  },
  {
    slug: 'parpola-1994-indus-script',
    title: 'Deciphering the Indus Script',
    sourceType: 'Book',
    author: 'Asko Parpola',
    publicationYear: 1994,
    publisher: 'Cambridge University Press',
    credibilityScore: 0.90,
    notes: 'The authoritative scholarly attempt at script decipherment.',
    nodeIds: ['indus-valley'],
    linkType: 'supports',
  },
  {
    slug: 'giosan-2012-harappan-rivers',
    title: 'Fluvial landscapes of the Harappan civilization',
    sourceType: 'Academic Paper',
    author: 'Liviu Giosan, Peter D. Clift, Mark G. Macklin, et al.',
    publicationYear: 2012,
    journal: 'Proceedings of the National Academy of Sciences',
    url: 'https://doi.org/10.1073/pnas.1112743109',
    credibilityScore: 0.90,
    notes: 'Key paper on river system changes and Harappan decline.',
    nodeIds: ['indus-valley'],
    linkType: 'supports',
  },

  // ── EASTER ISLAND ─────────────────────────────────────────────────────────

  {
    slug: 'vantilburg-1994-easter-island',
    title: 'Easter Island: Archaeology, Ecology and Culture',
    sourceType: 'Book',
    author: 'Jo Anne Van Tilburg',
    publicationYear: 1994,
    publisher: 'Smithsonian Institution Press',
    credibilityScore: 0.93,
    notes: 'The standard scholarly reference on Easter Island archaeology.',
    nodeIds: ['easter-island'],
    linkType: 'supports',
  },
  {
    slug: 'hunt-lipo-2011-statues',
    title: 'The Statues That Walked: Unraveling the Mystery of Easter Island',
    sourceType: 'Book',
    author: 'Terry L. Hunt, Carl P. Lipo',
    publicationYear: 2011,
    publisher: 'Free Press',
    credibilityScore: 0.87,
    notes: 'Presents the "walking" moai transport hypothesis and challenges the ecocide narrative.',
    nodeIds: ['easter-island'],
    linkType: 'supports',
  },
  {
    slug: 'lipo-2013-walking-moai',
    title: 'The "Walking" Megalithic Statues (Moai) of Easter Island',
    sourceType: 'Academic Paper',
    author: 'Carl P. Lipo, Terry L. Hunt, Sergio Rapu Haoa',
    publicationYear: 2013,
    journal: 'Journal of Archaeological Science',
    url: 'https://doi.org/10.1016/j.jas.2012.09.029',
    credibilityScore: 0.87,
    notes: 'Experimental archaeology demonstrating upright rocking transport method.',
    nodeIds: ['easter-island'],
    linkType: 'supports',
  },

  // ── YOUNGER DRYAS ─────────────────────────────────────────────────────────

  {
    slug: 'alley-2000-younger-dryas',
    title: 'The Younger Dryas Cold Interval as Viewed from Central Greenland',
    sourceType: 'Academic Paper',
    author: 'Richard B. Alley',
    publicationYear: 2000,
    journal: 'Quaternary Science Reviews',
    url: 'https://doi.org/10.1016/S0277-3791(99)00062-1',
    credibilityScore: 0.93,
    notes: 'Definitive review of the Younger Dryas from Greenland ice core data.',
    nodeIds: ['younger-dryas'],
    linkType: 'supports',
  },
  {
    slug: 'steffensen-2008-ice-core',
    title: 'High-Resolution Greenland Ice Core Data Show Abrupt Climate Change Happens in Few Years',
    sourceType: 'Academic Paper',
    author: 'J.P. Steffensen, K.K. Andersen, M. Bigler, et al.',
    publicationYear: 2008,
    journal: 'Science',
    url: 'https://doi.org/10.1126/science.1157707',
    credibilityScore: 0.95,
    notes: 'Shows onset of Younger Dryas warming occurred within 1–3 years.',
    nodeIds: ['younger-dryas'],
    linkType: 'supports',
  },

  // ── NABTA PLAYA ───────────────────────────────────────────────────────────

  {
    slug: 'wendorf-schild-1998-nabta',
    title: 'Nabta Playa and Its Role in Northeastern African Prehistory',
    sourceType: 'Academic Paper',
    author: 'Fred Wendorf, Romuald Schild',
    publicationYear: 1998,
    journal: 'Journal of Anthropological Archaeology',
    url: 'https://doi.org/10.1006/jare.1997.0195',
    credibilityScore: 0.90,
    notes: 'The lead excavators\' assessment of the site\'s regional significance.',
    nodeIds: ['nabta-playa'],
    linkType: 'supports',
  },
  {
    slug: 'malville-1998-nabta-astronomy',
    title: 'Megaliths and Neolithic astronomy in southern Egypt',
    sourceType: 'Academic Paper',
    author: 'J. McKim Malville, Fred Wendorf, Ali A. Mazar, Romuald Schild',
    publicationYear: 1998,
    journal: 'Nature',
    url: 'https://doi.org/10.1038/33299',
    credibilityScore: 0.88,
    notes: 'First peer-reviewed publication of proposed astronomical alignments.',
    nodeIds: ['nabta-playa', 'ancient-megalithic-sites'],
    linkType: 'supports',
  },

  // ── ANCIENT MEGALITHIC SITES ──────────────────────────────────────────────

  {
    slug: 'pearson-2012-stonehenge',
    title: 'Stonehenge: Exploring the Greatest Stone Age Mystery',
    sourceType: 'Book',
    author: 'Mike Parker Pearson',
    publicationYear: 2012,
    publisher: 'Simon & Schuster',
    credibilityScore: 0.92,
    notes: 'By the lead archaeologist of the Stonehenge Riverside Project.',
    nodeIds: ['ancient-megalithic-sites'],
    linkType: 'supports',
  },
  {
    slug: 'renfrew-1973-before-civ',
    title: 'Before Civilization: The Radiocarbon Revolution and Prehistoric Europe',
    sourceType: 'Book',
    author: 'Colin Renfrew',
    publicationYear: 1973,
    publisher: 'Jonathan Cape',
    credibilityScore: 0.90,
    notes: 'Established the independent development of European megaliths pre-dating Near Eastern influence.',
    nodeIds: ['ancient-megalithic-sites'],
    linkType: 'supports',
  },
  {
    slug: 'darvill-2006-stonehenge',
    title: 'Stonehenge: The Biography of a Landscape',
    sourceType: 'Book',
    author: 'Timothy Darvill',
    publicationYear: 2006,
    publisher: 'Tempus',
    credibilityScore: 0.90,
    notes: 'Comprehensive archaeological biography of Stonehenge within its landscape context.',
    nodeIds: ['ancient-megalithic-sites'],
    linkType: 'supports',
  },

  // ── GREAT PYRAMID ─────────────────────────────────────────────────────────

  {
    slug: 'lehner-1997-complete-pyramids',
    title: 'The Complete Pyramids: Solving the Ancient Mysteries',
    sourceType: 'Book',
    author: 'Mark Lehner',
    publicationYear: 1997,
    publisher: 'Thames & Hudson',
    credibilityScore: 0.96,
    notes: 'The definitive scholarly reference on Egyptian pyramids.',
    nodeIds: ['great-pyramid', 'sphinx', 'pyramid-construction-debate'],
    linkType: 'supports',
  },
  {
    slug: 'tallet-2014-wadi-al-jarf',
    title: 'The Harbor of Khufu on the Red Sea Coast at Wadi al-Jarf, Egypt',
    sourceType: 'Academic Paper',
    author: 'Pierre Tallet, Gregory Marouard',
    publicationYear: 2014,
    journal: 'Near Eastern Archaeology',
    url: 'https://doi.org/10.5615/neareastarch.77.1.0004',
    credibilityScore: 0.95,
    notes: 'Publication of the Wadi al-Jarf papyri — oldest papyri ever found, documenting Great Pyramid logistics.',
    nodeIds: ['great-pyramid', 'pyramid-construction-debate'],
    linkType: 'supports',
  },
  {
    slug: 'morishima-2017-void',
    title: 'Discovery of a big void in Khufu\'s Pyramid by observation of cosmic-ray muons',
    sourceType: 'Academic Paper',
    author: 'Kunihiro Morishima, Mitsuaki Kuno, Akira Nishio, et al.',
    publicationYear: 2017,
    journal: 'Nature',
    url: 'https://doi.org/10.1038/nature24647',
    credibilityScore: 0.93,
    notes: 'ScanPyramids muon tomography; confirms previously unknown void in the Great Pyramid.',
    nodeIds: ['great-pyramid'],
    linkType: 'supports',
  },
  {
    slug: 'lehner-hawass-2017-giza',
    title: 'Giza and the Pyramids',
    sourceType: 'Book',
    author: 'Mark Lehner, Zahi Hawass',
    publicationYear: 2017,
    publisher: 'University of Chicago Press',
    credibilityScore: 0.95,
    notes: 'Updated synthesis incorporating recent excavation data including the Wadi al-Jarf papyri.',
    nodeIds: ['great-pyramid', 'sphinx', 'pyramid-construction-debate'],
    linkType: 'supports',
  },

  // ── SPHINX ────────────────────────────────────────────────────────────────

  {
    slug: 'gauri-1995-sphinx-weathering',
    title: 'Geological Weathering and Its Implications on the Age of the Sphinx',
    sourceType: 'Academic Paper',
    author: 'K. Lal Gauri, John J. Sinai, Jayanta K. Bandyopadhyay',
    publicationYear: 1995,
    journal: 'Geoarchaeology',
    credibilityScore: 0.87,
    notes: 'Attributes Sphinx enclosure erosion to salt weathering and wind rather than water.',
    nodeIds: ['sphinx'],
    linkType: 'contradicts',
  },
  {
    slug: 'schoch-1999-voices',
    title: 'Voices of the Rocks: A Scientist Looks at Catastrophes and Ancient Civilizations',
    sourceType: 'Book',
    author: 'Robert M. Schoch, Robert Aquinas McNally',
    publicationYear: 1999,
    publisher: 'Harmony Books',
    credibilityScore: 0.58,
    notes: 'Presents Schoch\'s water erosion hypothesis and its implications for Sphinx dating. Minority position.',
    nodeIds: ['sphinx'],
    linkType: 'supports',
  },

  // ── PYRAMID CONSTRUCTION ─────────────────────────────────────────────────

  {
    slug: 'tallet-2017-papyri',
    title: 'Les papyrus de la mer Rouge I: Le "Journal de Merer"',
    sourceType: 'Archaeological Report',
    author: 'Pierre Tallet',
    publicationYear: 2017,
    publisher: 'IFAO',
    credibilityScore: 0.97,
    notes: 'Full publication of Inspector Merer\'s pyramid construction logbook.',
    nodeIds: ['pyramid-construction-debate', 'great-pyramid'],
    linkType: 'supports',
  },
  {
    slug: 'arnold-1991-building-egypt',
    title: 'Building in Egypt: Pharaonic Stone Masonry',
    sourceType: 'Book',
    author: 'Dieter Arnold',
    publicationYear: 1991,
    publisher: 'Oxford University Press',
    credibilityScore: 0.95,
    notes: 'Technical reference on Egyptian masonry methods; standard resource on quarrying and logistics.',
    nodeIds: ['pyramid-construction-debate'],
    linkType: 'supports',
  },

  // ── BOOK OF ENOCH ─────────────────────────────────────────────────────────

  {
    slug: 'milik-1976-enoch',
    title: 'The Books of Enoch: Aramaic Fragments of Qumrân Cave 4',
    sourceType: 'Book',
    author: 'Józef T. Milik',
    publicationYear: 1976,
    publisher: 'Oxford University Press',
    credibilityScore: 0.95,
    notes: 'The critical Aramaic text edition establishing multiple manuscript traditions from Qumran.',
    nodeIds: ['book-of-enoch', 'dead-sea-scrolls'],
    linkType: 'supports',
  },
  {
    slug: 'nickelsburg-2001-enoch-commentary',
    title: '1 Enoch 1: A Commentary on the Book of 1 Enoch, Chapters 1–36; 81–108',
    sourceType: 'Academic Paper',
    author: 'George W.E. Nickelsburg',
    publicationYear: 2001,
    publisher: 'Fortress Press',
    credibilityScore: 0.95,
    notes: 'The authoritative scholarly commentary on the Book of Watchers section.',
    nodeIds: ['book-of-enoch', 'watchers', 'nephilim'],
    linkType: 'references',
  },
  {
    slug: 'vanderkam-1984-enoch',
    title: 'Enoch and the Growth of an Apocalyptic Tradition',
    sourceType: 'Book',
    author: 'James C. VanderKam',
    publicationYear: 1984,
    publisher: 'Catholic Biblical Association of America',
    credibilityScore: 0.92,
    notes: 'Traces development of Enoch traditions from earliest texts through Qumran.',
    nodeIds: ['book-of-enoch'],
    linkType: 'supports',
  },
  {
    slug: 'knibb-1978-ethiopic-enoch',
    title: 'The Ethiopic Book of Enoch',
    sourceType: 'Religious Text',
    author: 'Michael A. Knibb',
    publicationYear: 1978,
    publisher: 'Oxford University Press',
    credibilityScore: 0.92,
    notes: 'Critical edition of the Ethiopic text with translation and notes.',
    nodeIds: ['book-of-enoch'],
    linkType: 'references',
  },

  // ── WATCHERS ─────────────────────────────────────────────────────────────

  {
    slug: 'annus-2010-watchers',
    title: 'On the Origin of the Watchers: A Comparative Study of the Antediluvian Wisdom in Mesopotamian and Jewish Traditions',
    sourceType: 'Academic Paper',
    author: 'Amar Annus',
    publicationYear: 2010,
    journal: 'Journal for the Study of the Pseudepigrapha',
    url: 'https://doi.org/10.1177/0951820710375549',
    credibilityScore: 0.88,
    notes: 'Demonstrates literary connections between Watcher tradition and Mesopotamian Apkallu sages.',
    nodeIds: ['watchers', 'book-of-enoch', 'comparative-mythology'],
    linkType: 'references',
  },
  {
    slug: 'kvanvig-1988-roots',
    title: 'Roots of Apocalyptic: The Mesopotamian Background of the Enoch Figure and of the Son of Man',
    sourceType: 'Book',
    author: 'Helge S. Kvanvig',
    publicationYear: 1988,
    publisher: 'Neukirchener Verlag',
    credibilityScore: 0.87,
    notes: 'Traces literary antecedents of the Enoch/Watcher tradition in Babylonian religious literature.',
    nodeIds: ['watchers', 'book-of-enoch'],
    linkType: 'references',
  },

  // ── NEPHILIM ──────────────────────────────────────────────────────────────

  {
    slug: 'hendel-1987-nephilim',
    title: 'Of Demigods and the Deluge: Toward an Interpretation of Genesis 6:1–4',
    sourceType: 'Academic Paper',
    author: 'Ronald S. Hendel',
    publicationYear: 1987,
    journal: 'Journal of Biblical Literature',
    url: 'https://doi.org/10.2307/3261007',
    credibilityScore: 0.90,
    notes: 'Establishes Nephilim as literary heirs of Mesopotamian divine-human hybrid traditions.',
    nodeIds: ['nephilim', 'giants-ancient-texts'],
    linkType: 'references',
  },
  {
    slug: 'stuckenbruck-2004-giants',
    title: 'Giant Mythology and Demonology: From Ancient Near East to the Dead Sea Scrolls',
    sourceType: 'Academic Paper',
    author: 'Loren T. Stuckenbruck',
    publicationYear: 2004,
    credibilityScore: 0.88,
    notes: 'Traces Nephilim traditions through Second Temple literature.',
    nodeIds: ['nephilim', 'book-of-enoch'],
    linkType: 'references',
  },

  // ── DEAD SEA SCROLLS ──────────────────────────────────────────────────────

  {
    slug: 'vermes-1997-dss',
    title: 'The Complete Dead Sea Scrolls in English',
    sourceType: 'Historical Text',
    author: 'Géza Vermes',
    publicationYear: 1997,
    publisher: 'Penguin',
    credibilityScore: 0.93,
    notes: 'Standard English translation widely used in academic contexts.',
    nodeIds: ['dead-sea-scrolls', 'book-of-enoch'],
    linkType: 'references',
  },
  {
    slug: 'schiffman-1994-reclaiming',
    title: 'Reclaiming the Dead Sea Scrolls',
    sourceType: 'Book',
    author: 'Lawrence H. Schiffman',
    publicationYear: 1994,
    publisher: 'Doubleday',
    credibilityScore: 0.92,
    notes: 'Essential scholarly overview of the scrolls\' content and community context.',
    nodeIds: ['dead-sea-scrolls'],
    linkType: 'supports',
  },
  {
    slug: 'cross-1995-library-qumran',
    title: 'The Ancient Library of Qumran',
    sourceType: 'Book',
    author: 'Frank Moore Cross',
    publicationYear: 1995,
    publisher: 'Fortress Press',
    credibilityScore: 0.93,
    notes: 'By one of the original scroll scholars; foundational for understanding the library\'s composition.',
    nodeIds: ['dead-sea-scrolls'],
    linkType: 'supports',
  },
  {
    slug: 'iaa-dss-digital',
    title: 'The Dead Sea Scrolls Digital Library',
    sourceType: 'Museum Archive',
    author: 'Israel Antiquities Authority',
    publicationYear: 2012,
    url: 'https://www.deadseascrolls.org.il/',
    credibilityScore: 0.95,
    notes: 'Official IAA digital repository. High-resolution imaging freely accessible online.',
    nodeIds: ['dead-sea-scrolls'],
    linkType: 'references',
  },

  // ── EPIC OF GILGAMESH ─────────────────────────────────────────────────────

  {
    slug: 'george-2003-gilgamesh',
    title: 'The Babylonian Gilgamesh Epic: Introduction, Critical Edition and Cuneiform Texts',
    sourceType: 'Historical Text',
    author: 'Andrew R. George',
    publicationYear: 2003,
    publisher: 'Oxford University Press',
    credibilityScore: 0.97,
    notes: 'The definitive modern scholarly edition; includes all cuneiform sources.',
    nodeIds: ['epic-of-gilgamesh', 'flood-narratives', 'sumerian-civilization'],
    linkType: 'references',
  },
  {
    slug: 'dalley-1989-myths-mesopotamia',
    title: 'Myths from Mesopotamia: Creation, the Flood, Gilgamesh, and Others',
    sourceType: 'Book',
    author: 'Stephanie Dalley',
    publicationYear: 1989,
    publisher: 'Oxford University Press',
    credibilityScore: 0.93,
    notes: 'Authoritative scholarly translation of the major Mesopotamian myths.',
    nodeIds: ['epic-of-gilgamesh', 'flood-narratives'],
    linkType: 'references',
  },
  {
    slug: 'tigay-1982-gilgamesh-evolution',
    title: 'The Evolution of the Gilgamesh Epic',
    sourceType: 'Book',
    author: 'Jeffrey H. Tigay',
    publicationYear: 1982,
    publisher: 'University of Pennsylvania Press',
    credibilityScore: 0.92,
    notes: 'Traces development of the epic from Sumerian precursors through the standard Babylonian version.',
    nodeIds: ['epic-of-gilgamesh'],
    linkType: 'supports',
  },

  // ── FLOOD NARRATIVES ─────────────────────────────────────────────────────

  {
    slug: 'lambert-millard-1969-atra-hasis',
    title: 'Atra-Hasis: The Babylonian Story of the Flood',
    sourceType: 'Historical Text',
    author: 'W.G. Lambert, A.R. Millard',
    publicationYear: 1969,
    publisher: 'Clarendon Press',
    credibilityScore: 0.93,
    notes: 'Primary scholarly edition of the Atra-Hasis epic — the oldest extant flood narrative.',
    nodeIds: ['flood-narratives', 'epic-of-gilgamesh'],
    linkType: 'references',
  },
  {
    slug: 'dundes-1988-flood-myth',
    title: 'The Flood Myth',
    sourceType: 'Book',
    author: 'Alan Dundes (ed.)',
    publicationYear: 1988,
    publisher: 'University of California Press',
    credibilityScore: 0.90,
    notes: 'Anthology of comparative mythology scholarship on flood traditions.',
    nodeIds: ['flood-narratives', 'comparative-mythology'],
    linkType: 'supports',
  },
  {
    slug: 'ryan-pitman-1998-noahs-flood',
    title: 'Noah\'s Flood: The New Scientific Discoveries about the Event That Changed History',
    sourceType: 'Book',
    author: 'William B.F. Ryan, Walter C. Pitman',
    publicationYear: 1998,
    publisher: 'Simon & Schuster',
    credibilityScore: 0.72,
    notes: 'Proposes Black Sea flood hypothesis; geological data is solid though connection to myths is debated.',
    nodeIds: ['flood-narratives'],
    linkType: 'supports',
  },

  // ── COMPARATIVE MYTHOLOGY ─────────────────────────────────────────────────

  {
    slug: 'campbell-1949-hero',
    title: 'The Hero with a Thousand Faces',
    sourceType: 'Book',
    author: 'Joseph Campbell',
    publicationYear: 1949,
    publisher: 'Princeton University Press',
    credibilityScore: 0.82,
    notes: 'Foundational work on the monomyth; influential but contested for over-generalisation.',
    nodeIds: ['comparative-mythology'],
    linkType: 'supports',
  },
  {
    slug: 'witzel-2012-origins-mythologies',
    title: 'The Origins of the World\'s Mythologies',
    sourceType: 'Book',
    author: 'E.J. Michael Witzel',
    publicationYear: 2012,
    publisher: 'Oxford University Press',
    credibilityScore: 0.88,
    notes: 'Rigorous phylogenetic approach to comparative mythology.',
    nodeIds: ['comparative-mythology', 'dragon-traditions', 'giants-ancient-texts'],
    linkType: 'supports',
  },
  {
    slug: 'dumezil-1969-warrior',
    title: 'The Destiny of the Warrior',
    sourceType: 'Book',
    author: 'Georges Dumézil',
    publicationYear: 1969,
    publisher: 'University of Chicago Press',
    credibilityScore: 0.90,
    notes: 'Part of Dumézil\'s trilogy on Indo-European trifunctional ideology.',
    nodeIds: ['comparative-mythology'],
    linkType: 'supports',
  },

  // ── ROSWELL ───────────────────────────────────────────────────────────────

  {
    slug: 'usaf-1994-roswell-report',
    title: 'The Roswell Report: Fact versus Fiction in the New Mexico Desert',
    sourceType: 'Government Document',
    author: 'Richard L. Weaver, James McAndrew',
    publicationYear: 1994,
    url: 'https://media.defense.gov/2010/Oct/27/2001329594/-1/-1/0/AFD-101027-030.pdf',
    credibilityScore: 0.88,
    notes: 'Official USAF investigation concluding debris was from Project Mogul.',
    nodeIds: ['roswell-incident'],
    linkType: 'contradicts',
  },
  {
    slug: 'usaf-1997-roswell-case-closed',
    title: 'The Roswell Report: Case Closed',
    sourceType: 'Government Document',
    author: 'James McAndrew',
    publicationYear: 1997,
    credibilityScore: 0.88,
    notes: 'Second official USAF report addressing witness descriptions of bodies.',
    nodeIds: ['roswell-incident'],
    linkType: 'contradicts',
  },
  {
    slug: 'saler-1997-roswell-myth',
    title: 'UFO Crash at Roswell: The Genesis of a Modern Myth',
    sourceType: 'Book',
    author: 'Benson Saler, Charles A. Ziegler, Charles B. Moore',
    publicationYear: 1997,
    publisher: 'Smithsonian Institution Press',
    credibilityScore: 0.87,
    notes: 'Anthropological and scientific analysis of the incident and the mythology that developed around it.',
    nodeIds: ['roswell-incident'],
    linkType: 'references',
  },

  // ── PENTAGON UAP ─────────────────────────────────────────────────────────

  {
    slug: 'odni-2021-uap',
    title: 'Preliminary Assessment: Unidentified Aerial Phenomena',
    sourceType: 'Government Document',
    author: 'Office of the Director of National Intelligence',
    publicationYear: 2021,
    url: 'https://www.dni.gov/files/ODNI/documents/assessments/Prelimary-Assessment-UAP-20210625.pdf',
    credibilityScore: 0.90,
    notes: 'ODNI report acknowledging 144 UAP reports; only one definitively explained.',
    nodeIds: ['pentagon-uap-reports'],
    linkType: 'references',
  },
  {
    slug: 'dod-2022-aaro',
    title: 'Establishment of the All-domain Anomaly Resolution Office',
    sourceType: 'Government Document',
    author: 'U.S. Department of Defense',
    publicationYear: 2022,
    url: 'https://media.defense.gov/2022/Jul/20/2003033410/-1/-1/1/ESTABLISHMENT-OF-THE-ALL-DOMAIN-ANOMALY-RESOLUTION-OFFICE.PDF',
    credibilityScore: 0.90,
    notes: 'DoD directive establishing AARO; formalises ongoing government UAP investigation.',
    nodeIds: ['pentagon-uap-reports'],
    linkType: 'references',
  },
  {
    slug: 'cooper-2017-pentagon-ufo',
    title: 'Glowing Auras and "Black Money": The Pentagon\'s Mysterious U.F.O. Program',
    sourceType: 'News Investigation',
    author: 'Helene Cooper, Ralph Blumenthal, Leslie Kean',
    publicationYear: 2017,
    url: 'https://www.nytimes.com/2017/12/16/us/politics/pentagon-program-ufo-harry-reid.html',
    credibilityScore: 0.82,
    notes: 'NYT investigation disclosing AATIP; triggered formal government acknowledgment.',
    nodeIds: ['pentagon-uap-reports', 'roswell-incident'],
    linkType: 'references',
  },
  {
    slug: 'aaro-2024-historical',
    title: 'AARO Historical Record Report Volume 1',
    sourceType: 'Government Document',
    author: 'All-domain Anomaly Resolution Office (AARO)',
    publicationYear: 2024,
    url: 'https://www.aaro.mil/Portals/136/PDFs/AARO_Historical_Record_Report_Vol1_2024.pdf',
    credibilityScore: 0.90,
    notes: 'Finds no verified evidence of non-human intelligence in historical UAP reports.',
    nodeIds: ['pentagon-uap-reports'],
    linkType: 'references',
  },

  // ── RENDLESHAM ────────────────────────────────────────────────────────────

  {
    slug: 'halt-1981-memo',
    title: 'Memorandum for 01 AF: Unexplained Lights',
    sourceType: 'Government Document',
    author: 'Lt. Col. Charles I. Halt',
    publicationYear: 1981,
    credibilityScore: 0.85,
    notes: 'Contemporaneous official USAF memo to UK Ministry of Defence. Genuine primary document.',
    nodeIds: ['rendlesham-forest'],
    linkType: 'references',
  },
  {
    slug: 'ridpath-rendlesham',
    title: 'The Rendlesham Forest UFO case',
    sourceType: 'News Investigation',
    author: 'Ian Ridpath',
    publicationYear: 2021,
    url: 'https://www.ianridpath.com/ufo/rendlesham.htm',
    credibilityScore: 0.75,
    notes: 'Comprehensive skeptical analysis identifying the Orfordness lighthouse as the primary stimulus.',
    nodeIds: ['rendlesham-forest'],
    linkType: 'contradicts',
  },

  // ── ANCIENT ASTRONAUT HYPOTHESIS ─────────────────────────────────────────

  {
    slug: 'feder-2010-dubious-archaeology',
    title: 'Encyclopedia of Dubious Archaeology: From Atlantis to the Walam Olum',
    sourceType: 'Book',
    author: 'Kenneth L. Feder',
    publicationYear: 2010,
    publisher: 'Greenwood Press',
    credibilityScore: 0.87,
    notes: 'Systematic scholarly refutation of ancient astronaut and pseudoarchaeology claims.',
    nodeIds: ['ancient-astronaut-hypothesis'],
    linkType: 'contradicts',
  },
  {
    slug: 'fritze-2009-invented-knowledge',
    title: 'Invented Knowledge: False History, Fake Science and Pseudo-Religions',
    sourceType: 'Book',
    author: 'Ronald H. Fritze',
    publicationYear: 2009,
    publisher: 'Reaktion Books',
    credibilityScore: 0.85,
    notes: 'Contextualises ancient astronaut hypothesis within broader history of pseudoscience.',
    nodeIds: ['ancient-astronaut-hypothesis'],
    linkType: 'contradicts',
  },
  {
    slug: 'daniken-1968-chariots',
    title: 'Chariots of the Gods? Unsolved Mysteries of the Past',
    sourceType: 'Book',
    author: 'Erich von Däniken',
    publicationYear: 1968,
    publisher: 'Putnam',
    credibilityScore: 0.38,
    notes: 'The foundational popular work of the ancient astronaut hypothesis. Included as primary source document.',
    nodeIds: ['ancient-astronaut-hypothesis'],
    linkType: 'supports',
  },

  // ── HUMAN EVOLUTION ───────────────────────────────────────────────────────

  {
    slug: 'white-2009-ardipithecus',
    title: 'Ardipithecus ramidus and the Paleobiology of Early Hominids',
    sourceType: 'Academic Paper',
    author: 'Tim D. White, Berhane Asfaw, Yonas Beyene, et al.',
    publicationYear: 2009,
    journal: 'Science',
    url: 'https://doi.org/10.1126/science.1175802',
    credibilityScore: 0.97,
    notes: 'Pushes back bipedal hominin record to 4.4 million years ago.',
    nodeIds: ['human-evolution'],
    linkType: 'supports',
  },
  {
    slug: 'reich-2018-who-we-are',
    title: 'Who We Are and How We Got Here: Ancient DNA and the New Science of the Human Past',
    sourceType: 'Book',
    author: 'David Reich',
    publicationYear: 2018,
    publisher: 'Pantheon Books',
    credibilityScore: 0.95,
    notes: 'By the leading ancient DNA researcher; covers Neanderthal/Denisovan interbreeding and migration.',
    nodeIds: ['human-evolution', 'neanderthals', 'denisovans', 'human-migration'],
    linkType: 'supports',
  },
  {
    slug: 'hublin-2017-jebel-irhoud',
    title: 'New fossils from Jebel Irhoud, Morocco and the pan-African origin of Homo sapiens',
    sourceType: 'Academic Paper',
    author: 'Jean-Jacques Hublin, Abdelouahed Ben-Ncer, Shara E. Bailey, et al.',
    publicationYear: 2017,
    journal: 'Nature',
    url: 'https://doi.org/10.1038/nature22336',
    credibilityScore: 0.97,
    notes: 'Pushes anatomically modern human origin to ~315,000 years ago.',
    nodeIds: ['human-evolution', 'human-migration'],
    linkType: 'supports',
  },

  // ── NEANDERTHALS ──────────────────────────────────────────────────────────

  {
    slug: 'green-2010-neandertal-genome',
    title: 'A Draft Sequence of the Neandertal Genome',
    sourceType: 'Academic Paper',
    author: 'Richard E. Green, Johannes Krause, Adrian W. Briggs, et al.',
    publicationYear: 2010,
    journal: 'Science',
    url: 'https://doi.org/10.1126/science.1188021',
    credibilityScore: 0.98,
    notes: 'Landmark paper confirming interbreeding with modern humans.',
    nodeIds: ['neanderthals', 'human-evolution', 'denisovans'],
    linkType: 'supports',
  },
  {
    slug: 'paabo-2014-neanderthal-man',
    title: 'Neanderthal Man: In Search of Lost Genomes',
    sourceType: 'Book',
    author: 'Svante Pääbo',
    publicationYear: 2014,
    publisher: 'Basic Books',
    credibilityScore: 0.97,
    notes: 'Memoir by the 2022 Nobel laureate who sequenced the Neanderthal genome.',
    nodeIds: ['neanderthals', 'denisovans'],
    linkType: 'supports',
  },
  {
    slug: 'zilhao-2010-neanderthal-symbolic',
    title: 'Symbolic use of marine shells and mineral pigments by Iberian Neandertals',
    sourceType: 'Academic Paper',
    author: 'João Zilhão, Diego E. Angelucci, Ernestina Badal-García, et al.',
    publicationYear: 2010,
    journal: 'Proceedings of the National Academy of Sciences',
    url: 'https://doi.org/10.1073/pnas.0914088107',
    credibilityScore: 0.90,
    notes: 'Evidence of Neanderthal symbolic behavior including pigment use.',
    nodeIds: ['neanderthals'],
    linkType: 'supports',
  },

  // ── DENISOVANS ────────────────────────────────────────────────────────────

  {
    slug: 'reich-2010-denisovans',
    title: 'Genetic history of an archaic hominin group from Denisova Cave in Siberia',
    sourceType: 'Academic Paper',
    author: 'David Reich, Richard E. Green, Martin Kircher, et al.',
    publicationYear: 2010,
    journal: 'Nature',
    url: 'https://doi.org/10.1038/nature09710',
    credibilityScore: 0.98,
    notes: 'The founding paper defining Denisovans as a distinct archaic human lineage.',
    nodeIds: ['denisovans'],
    linkType: 'supports',
  },
  {
    slug: 'slon-2018-hybrid',
    title: 'The genome of the offspring of a Neanderthal mother and a Denisovan father',
    sourceType: 'Academic Paper',
    author: 'Viviane Slon, Fabrizio Mafessoni, Benjamin Vernot, et al.',
    publicationYear: 2018,
    journal: 'Nature',
    url: 'https://doi.org/10.1038/s41586-018-0455-x',
    credibilityScore: 0.98,
    notes: 'Analysis of Denisova 11, a first-generation Neanderthal-Denisovan hybrid.',
    nodeIds: ['denisovans', 'neanderthals'],
    linkType: 'supports',
  },
  {
    slug: 'chen-2019-xiahe-mandible',
    title: 'A late Middle Pleistocene Denisovan mandible from the Tibetan Plateau',
    sourceType: 'Academic Paper',
    author: 'Fahu Chen, Frido Welker, Chuan-Chou Shen, et al.',
    publicationYear: 2019,
    journal: 'Nature',
    url: 'https://doi.org/10.1038/s41586-019-1139-x',
    credibilityScore: 0.96,
    notes: 'Identifies the Xiahe mandible as Denisovan; extends their range to the Tibetan Plateau.',
    nodeIds: ['denisovans'],
    linkType: 'supports',
  },

  // ── STONED APE ────────────────────────────────────────────────────────────

  {
    slug: 'mckenna-1992-food-of-gods',
    title: 'Food of the Gods: The Search for the Original Tree of Knowledge',
    sourceType: 'Book',
    author: 'Terence McKenna',
    publicationYear: 1992,
    publisher: 'Bantam Books',
    credibilityScore: 0.42,
    notes: 'The original Stoned Ape Theory. Not accepted by mainstream evolutionary biology.',
    nodeIds: ['stoned-ape-theory'],
    linkType: 'supports',
  },
  {
    slug: 'griffiths-2016-psilocybin',
    title: 'Psilocybin produces substantial and sustained decreases in depression and anxiety',
    sourceType: 'Academic Paper',
    author: 'Roland Griffiths, Matthew Johnson, Michael Carducci, et al.',
    publicationYear: 2016,
    journal: 'Journal of Psychopharmacology',
    url: 'https://doi.org/10.1177/0269881116675513',
    credibilityScore: 0.90,
    notes: 'Documents real neurological effects of psilocybin; does not support evolutionary claims.',
    nodeIds: ['stoned-ape-theory', 'mystery-schools'],
    linkType: 'references',
  },
  {
    slug: 'stringer-2012-lone-survivors',
    title: 'Lone Survivors: How We Came to Be the Only Humans on Earth',
    sourceType: 'Book',
    author: 'Chris Stringer',
    publicationYear: 2012,
    publisher: 'Times Books',
    credibilityScore: 0.93,
    notes: 'Mainstream account of human cognitive evolution; context against which to evaluate McKenna\'s claims.',
    nodeIds: ['stoned-ape-theory', 'human-evolution', 'human-migration'],
    linkType: 'contradicts',
  },

  // ── HUMAN MIGRATION ───────────────────────────────────────────────────────

  {
    slug: 'li-2008-genome-variation',
    title: 'Worldwide human relationships inferred from genome-wide patterns of variation',
    sourceType: 'Academic Paper',
    author: 'Jun Z. Li, Devin M. Absher, Hua Tang, et al.',
    publicationYear: 2008,
    journal: 'Science',
    url: 'https://doi.org/10.1126/science.1153717',
    credibilityScore: 0.95,
    notes: 'Population genetics study across 51 world populations confirming African origin.',
    nodeIds: ['human-migration', 'human-evolution'],
    linkType: 'supports',
  },
  {
    slug: 'henn-2011-hunter-gatherer',
    title: 'Hunter-gatherer genomic diversity suggests a southern African origin for modern humans',
    sourceType: 'Academic Paper',
    author: 'Brenna M. Henn, Christopher R. Gignoux, Matthew Jobin, et al.',
    publicationYear: 2011,
    journal: 'Proceedings of the National Academy of Sciences',
    url: 'https://doi.org/10.1073/pnas.1017511108',
    credibilityScore: 0.93,
    notes: 'Genetic evidence for southern Africa as the region of greatest modern human diversity.',
    nodeIds: ['human-migration'],
    linkType: 'supports',
  },

  // ── SIMULATION HYPOTHESIS ─────────────────────────────────────────────────

  {
    slug: 'bostrom-2003-simulation',
    title: 'Are You Living in a Computer Simulation?',
    sourceType: 'Academic Paper',
    author: 'Nick Bostrom',
    publicationYear: 2003,
    journal: 'Philosophical Quarterly',
    url: 'https://doi.org/10.1093/philq/53.211.243',
    credibilityScore: 0.85,
    notes: 'The formal philosophical statement of the simulation argument.',
    nodeIds: ['simulation-hypothesis'],
    linkType: 'supports',
  },
  {
    slug: 'chalmers-2022-reality-plus',
    title: 'Reality+: Virtual Worlds and the Philosophy of Mind',
    sourceType: 'Book',
    author: 'David J. Chalmers',
    publicationYear: 2022,
    publisher: 'W.W. Norton',
    credibilityScore: 0.85,
    notes: 'Philosopher of mind argues virtual worlds are genuine reality; serious philosophical treatment.',
    nodeIds: ['simulation-hypothesis', 'hard-problem-consciousness'],
    linkType: 'supports',
  },
  {
    slug: 'beane-2014-simulation-constraints',
    title: 'Constraints on the Universe as a Numerical Simulation',
    sourceType: 'Academic Paper',
    author: 'Silas R. Beane, Zohreh Davoudi, Martin J. Savage',
    publicationYear: 2014,
    journal: 'European Physical Journal A',
    url: 'https://doi.org/10.1140/epja/i2014-14148-0',
    credibilityScore: 0.80,
    notes: 'Proposes lattice structure test that could detect a simulation; found no compelling evidence.',
    nodeIds: ['simulation-hypothesis'],
    linkType: 'references',
  },

  // ── HARD PROBLEM OF CONSCIOUSNESS ─────────────────────────────────────────

  {
    slug: 'chalmers-1996-conscious-mind',
    title: 'The Conscious Mind: In Search of a Fundamental Theory',
    sourceType: 'Book',
    author: 'David J. Chalmers',
    publicationYear: 1996,
    publisher: 'Oxford University Press',
    credibilityScore: 0.92,
    notes: 'The book that formally introduced the "hard problem of consciousness."',
    nodeIds: ['hard-problem-consciousness'],
    linkType: 'supports',
  },
  {
    slug: 'nagel-1974-bat',
    title: 'What Is It Like to Be a Bat?',
    sourceType: 'Academic Paper',
    author: 'Thomas Nagel',
    publicationYear: 1974,
    journal: 'Philosophical Review',
    url: 'https://doi.org/10.2307/2183914',
    credibilityScore: 0.93,
    notes: 'The classic paper on the "explanatory gap"; essential background to the hard problem.',
    nodeIds: ['hard-problem-consciousness'],
    linkType: 'supports',
  },
  {
    slug: 'dennett-1991-consciousness-explained',
    title: 'Consciousness Explained',
    sourceType: 'Book',
    author: 'Daniel C. Dennett',
    publicationYear: 1991,
    publisher: 'Little, Brown',
    credibilityScore: 0.87,
    notes: 'The major materialist counterargument; Dennett denies qualia as popularly conceived.',
    nodeIds: ['hard-problem-consciousness'],
    linkType: 'contradicts',
  },
  {
    slug: 'tononi-2008-iit',
    title: 'Consciousness as Integrated Information: A Provisional Manifesto',
    sourceType: 'Academic Paper',
    author: 'Giulio Tononi',
    publicationYear: 2008,
    journal: 'Biological Bulletin',
    url: 'https://doi.org/10.2307/25470707',
    credibilityScore: 0.83,
    notes: 'Formal statement of Integrated Information Theory (IIT).',
    nodeIds: ['hard-problem-consciousness', 'quantum-consciousness'],
    linkType: 'references',
  },

  // ── QUANTUM CONSCIOUSNESS ─────────────────────────────────────────────────

  {
    slug: 'penrose-1989-emperors-new-mind',
    title: 'The Emperor\'s New Mind: Concerning Computers, Minds, and the Laws of Physics',
    sourceType: 'Book',
    author: 'Roger Penrose',
    publicationYear: 1989,
    publisher: 'Oxford University Press',
    credibilityScore: 0.80,
    notes: 'Philosophical and mathematical foundation for Penrose\'s non-computational consciousness argument.',
    nodeIds: ['quantum-consciousness'],
    linkType: 'supports',
  },
  {
    slug: 'tegmark-2000-decoherence',
    title: 'The importance of quantum decoherence in brain processes',
    sourceType: 'Academic Paper',
    author: 'Max Tegmark',
    publicationYear: 2000,
    journal: 'Physical Review E',
    url: 'https://doi.org/10.1103/PhysRevE.61.4194',
    credibilityScore: 0.90,
    notes: 'Calculates decoherence times in the brain are too short for Orch-OR; the primary physics objection.',
    nodeIds: ['quantum-consciousness'],
    linkType: 'contradicts',
  },
  {
    slug: 'koch-hepp-2006-quantum-brain',
    title: 'Quantum mechanics in the brain',
    sourceType: 'Academic Paper',
    author: 'Christof Koch, Klaus Hepp',
    publicationYear: 2006,
    journal: 'Nature',
    url: 'https://doi.org/10.1038/440611a',
    credibilityScore: 0.88,
    notes: 'Review arguing quantum effects unlikely to play a significant role in neural computation.',
    nodeIds: ['quantum-consciousness'],
    linkType: 'contradicts',
  },

  // ── COLLECTIVE UNCONSCIOUS ────────────────────────────────────────────────

  {
    slug: 'jung-1959-archetypes',
    title: 'The Archetypes and the Collective Unconscious (Collected Works Vol. 9 Part I)',
    sourceType: 'Book',
    author: 'C.G. Jung',
    publicationYear: 1959,
    publisher: 'Princeton University Press',
    credibilityScore: 0.78,
    notes: 'Primary statement of Jung\'s theory of archetypes and the collective unconscious.',
    nodeIds: ['collective-unconscious', 'comparative-mythology'],
    linkType: 'supports',
  },
  {
    slug: 'stevens-2002-archetype-revisited',
    title: 'Archetypes Revisited: An Updated Natural History of the Self',
    sourceType: 'Book',
    author: 'Anthony Stevens',
    publicationYear: 2002,
    publisher: 'Brunner-Routledge',
    credibilityScore: 0.73,
    notes: 'Attempts to ground Jungian archetypes in evolutionary biology.',
    nodeIds: ['collective-unconscious'],
    linkType: 'references',
  },

  // ── FREEMASONRY ───────────────────────────────────────────────────────────

  {
    slug: 'stevenson-1988-origins-freemasonry',
    title: 'The Origins of Freemasonry: Scotland\'s Century, 1590–1710',
    sourceType: 'Book',
    author: 'David Stevenson',
    publicationYear: 1988,
    publisher: 'Cambridge University Press',
    credibilityScore: 0.92,
    notes: 'Definitive scholarly account of Freemasonry\'s documented origins using lodge records.',
    nodeIds: ['freemasonry'],
    linkType: 'supports',
  },
  {
    slug: 'jacob-1981-radical-enlightenment',
    title: 'The Radical Enlightenment: Pantheists, Freemasons and Republicans',
    sourceType: 'Book',
    author: 'Margaret C. Jacob',
    publicationYear: 1981,
    publisher: 'Allen & Unwin',
    credibilityScore: 0.90,
    notes: 'Scholarly analysis of Masonic lodges as carriers of Enlightenment political ideas.',
    nodeIds: ['freemasonry', 'illuminati-history'],
    linkType: 'supports',
  },
  {
    slug: 'jacob-1991-living-enlightenment',
    title: 'Living the Enlightenment: Freemasonry and Politics in Eighteenth-Century Europe',
    sourceType: 'Book',
    author: 'Margaret C. Jacob',
    publicationYear: 1991,
    publisher: 'Oxford University Press',
    credibilityScore: 0.90,
    notes: 'Documents the actual political activities of Masonic lodges, distinguishing fact from myth.',
    nodeIds: ['freemasonry'],
    linkType: 'supports',
  },

  // ── ROSICRUCIANISM ────────────────────────────────────────────────────────

  {
    slug: 'yates-1972-rosicrucian-enlightenment',
    title: 'The Rosicrucian Enlightenment',
    sourceType: 'Book',
    author: 'Frances A. Yates',
    publicationYear: 1972,
    publisher: 'Routledge',
    credibilityScore: 0.92,
    notes: 'The foundational scholarly work on Rosicrucianism and early modern natural philosophy.',
    nodeIds: ['rosicrucianism', 'freemasonry', 'hermeticism'],
    linkType: 'supports',
  },
  {
    slug: 'mcintosh-1998-rosicrucians',
    title: 'The Rosicrucians: The History, Mythology, and Rituals of an Esoteric Order',
    sourceType: 'Book',
    author: 'Christopher McIntosh',
    publicationYear: 1998,
    publisher: 'Weiser Books',
    credibilityScore: 0.80,
    notes: 'Accessible scholarly overview of the Rosicrucian movement from manifestos to present.',
    nodeIds: ['rosicrucianism'],
    linkType: 'supports',
  },

  // ── HERMETICISM ───────────────────────────────────────────────────────────

  {
    slug: 'fowden-1986-egyptian-hermes',
    title: 'The Egyptian Hermes: A Historical Approach to the Late Pagan Mind',
    sourceType: 'Book',
    author: 'Garth Fowden',
    publicationYear: 1986,
    publisher: 'Cambridge University Press',
    credibilityScore: 0.93,
    notes: 'Definitive scholarly account of the Hermetic tradition\'s Alexandrian origins.',
    nodeIds: ['hermeticism', 'mystery-schools'],
    linkType: 'supports',
  },
  {
    slug: 'copenhaver-1992-hermetica',
    title: 'Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius',
    sourceType: 'Historical Text',
    author: 'Brian P. Copenhaver',
    publicationYear: 1992,
    publisher: 'Cambridge University Press',
    credibilityScore: 0.95,
    notes: 'The standard modern scholarly translation of the Hermetic corpus.',
    nodeIds: ['hermeticism'],
    linkType: 'references',
  },
  {
    slug: 'yates-1964-giordano-bruno',
    title: 'Giordano Bruno and the Hermetic Tradition',
    sourceType: 'Book',
    author: 'Frances A. Yates',
    publicationYear: 1964,
    publisher: 'University of Chicago Press',
    credibilityScore: 0.92,
    notes: 'Traces Hermetic influence on Renaissance natural philosophy through Ficino, Pico, and Bruno.',
    nodeIds: ['hermeticism', 'rosicrucianism'],
    linkType: 'supports',
  },

  // ── ILLUMINATI ────────────────────────────────────────────────────────────

  {
    slug: 'roberts-1972-mythology-secret-societies',
    title: 'The Mythology of the Secret Societies',
    sourceType: 'Book',
    author: 'J.M. Roberts',
    publicationYear: 1972,
    publisher: 'Secker & Warburg',
    credibilityScore: 0.88,
    notes: 'Scholarly history of conspiracy theories about secret societies including the Illuminati.',
    nodeIds: ['illuminati-history', 'freemasonry'],
    linkType: 'references',
  },
  {
    slug: 'billington-1980-fire',
    title: 'Fire in the Minds of Men: Origins of the Revolutionary Faith',
    sourceType: 'Book',
    author: 'James H. Billington',
    publicationYear: 1980,
    publisher: 'Basic Books',
    credibilityScore: 0.87,
    notes: 'By the Librarian of Congress; places the Illuminati in the context of revolutionary thought.',
    nodeIds: ['illuminati-history'],
    linkType: 'supports',
  },

  // ── MYSTERY SCHOOLS ───────────────────────────────────────────────────────

  {
    slug: 'burkert-1987-mystery-cults',
    title: 'Ancient Mystery Cults',
    sourceType: 'Book',
    author: 'Walter Burkert',
    publicationYear: 1987,
    publisher: 'Harvard University Press',
    credibilityScore: 0.95,
    notes: 'Definitive scholarly analysis of Greek mystery religions based on classical sources and archaeology.',
    nodeIds: ['mystery-schools'],
    linkType: 'supports',
  },
  {
    slug: 'kerenyi-1967-eleusis',
    title: 'Eleusis: Archetypal Image of Mother and Daughter',
    sourceType: 'Book',
    author: 'Carl Kerényi',
    publicationYear: 1967,
    publisher: 'Pantheon Books',
    credibilityScore: 0.88,
    notes: 'Classical scholar\'s analysis of the Eleusinian Mysteries; standard reference.',
    nodeIds: ['mystery-schools'],
    linkType: 'supports',
  },
  {
    slug: 'wasson-1978-road-to-eleusis',
    title: 'The Road to Eleusis: Unveiling the Secret of the Mysteries',
    sourceType: 'Book',
    author: 'R. Gordon Wasson, Albert Hofmann, Carl A.P. Ruck',
    publicationYear: 1978,
    publisher: 'Harcourt Brace',
    credibilityScore: 0.73,
    notes: 'Proposes the kykeon contained ergot-derived psychedelics. Minority hypothesis among classicists.',
    nodeIds: ['mystery-schools', 'stoned-ape-theory'],
    linkType: 'supports',
  },
  {
    slug: 'meyer-1987-ancient-mysteries',
    title: 'The Ancient Mysteries: A Sourcebook of Sacred Texts',
    sourceType: 'Historical Text',
    author: 'Marvin W. Meyer (ed.)',
    publicationYear: 1987,
    publisher: 'Harper & Row',
    credibilityScore: 0.90,
    notes: 'Primary source collection for Eleusinian, Orphic, Pythagorean, Dionysian, Mithraic, and Isis mysteries.',
    nodeIds: ['mystery-schools'],
    linkType: 'references',
  },

  // ── BRONZE AGE COLLAPSE ───────────────────────────────────────────────────

  {
    slug: 'cline-2014-1177bc',
    title: '1177 B.C.: The Year Civilization Collapsed',
    sourceType: 'Book',
    author: 'Eric H. Cline',
    publicationYear: 2014,
    publisher: 'Princeton University Press',
    credibilityScore: 0.93,
    notes: 'The leading scholarly synthesis; integrates archaeological, textual, and paleoclimate evidence.',
    nodeIds: ['bronze-age-collapse'],
    linkType: 'supports',
  },
  {
    slug: 'drews-1993-end-bronze-age',
    title: 'The End of the Bronze Age: Changes in Warfare and the Catastrophe ca. 1200 B.C.',
    sourceType: 'Book',
    author: 'Robert Drews',
    publicationYear: 1993,
    publisher: 'Princeton University Press',
    credibilityScore: 0.88,
    notes: 'Proposes changes in military technology as primary cause; influential though contested.',
    nodeIds: ['bronze-age-collapse'],
    linkType: 'supports',
  },
  {
    slug: 'drake-2012-climate-bronze-age',
    title: 'The Rapid Climate Change of the Late Bronze Age Collapse',
    sourceType: 'Academic Paper',
    author: 'Brandon Drake',
    publicationYear: 2012,
    journal: 'Journal of Archaeological Science',
    url: 'https://doi.org/10.1016/j.jas.2012.05.009',
    credibilityScore: 0.90,
    notes: 'Paleoclimate data demonstrating 300-year drought beginning c. 1200 BCE.',
    nodeIds: ['bronze-age-collapse'],
    linkType: 'supports',
  },
  {
    slug: 'tainter-1988-collapse',
    title: 'The Collapse of Complex Societies',
    sourceType: 'Book',
    author: 'Joseph A. Tainter',
    publicationYear: 1988,
    publisher: 'Cambridge University Press',
    credibilityScore: 0.90,
    notes: 'Theoretical framework for societal collapse; widely applied to the Bronze Age Collapse.',
    nodeIds: ['bronze-age-collapse'],
    linkType: 'references',
  },

  // ── ANTIKYTHERA MECHANISM ─────────────────────────────────────────────────

  {
    slug: 'freeth-2006-antikythera',
    title: 'Decoding the ancient Greek astronomical calculator known as the Antikythera Mechanism',
    sourceType: 'Academic Paper',
    author: 'Tony Freeth, Yanis Bitsakis, Xenophon Moussas, et al.',
    publicationYear: 2006,
    journal: 'Nature',
    url: 'https://doi.org/10.1038/nature05357',
    credibilityScore: 0.97,
    notes: 'The landmark CT-scanning paper that decoded the Mechanism\'s gearing and astronomical functions.',
    nodeIds: ['antikythera-mechanism'],
    linkType: 'supports',
  },
  {
    slug: 'freeth-2021-cosmos',
    title: 'A Model of the Cosmos in the ancient Greek Antikythera Mechanism',
    sourceType: 'Academic Paper',
    author: 'Tony Freeth, David Higgon, Aris Dacanalis, et al.',
    publicationYear: 2021,
    journal: 'Scientific Reports',
    url: 'https://doi.org/10.1038/s41598-021-84310-w',
    credibilityScore: 0.96,
    notes: 'Demonstrates the Mechanism tracked all five visible planets known to the ancient Greeks.',
    nodeIds: ['antikythera-mechanism'],
    linkType: 'supports',
  },
  {
    slug: 'price-1974-gears',
    title: 'Gears from the Greeks: The Antikythera Mechanism — A Calendar Computer from ca. 80 B.C.',
    sourceType: 'Academic Paper',
    author: 'Derek J. de Solla Price',
    publicationYear: 1974,
    journal: 'Transactions of the American Philosophical Society',
    credibilityScore: 0.93,
    notes: 'The foundational analytical study establishing the Mechanism\'s astronomical function.',
    nodeIds: ['antikythera-mechanism'],
    linkType: 'supports',
  },

  // ── YOUNGER DRYAS IMPACT ──────────────────────────────────────────────────

  {
    slug: 'firestone-2007-impact',
    title: 'Evidence for an extraterrestrial impact 12,900 years ago that contributed to the megafaunal extinctions and the Younger Dryas cooling',
    sourceType: 'Academic Paper',
    author: 'R.B. Firestone, A. West, J.P. Kennett, et al.',
    publicationYear: 2007,
    journal: 'Proceedings of the National Academy of Sciences',
    url: 'https://doi.org/10.1073/pnas.0706977104',
    credibilityScore: 0.78,
    notes: 'The original impact hypothesis paper; extensively debated in subsequent peer-reviewed literature.',
    nodeIds: ['younger-dryas-impact', 'younger-dryas'],
    linkType: 'supports',
  },
  {
    slug: 'boslough-2012-arguments-against',
    title: 'Arguments and Evidence Against a Younger Dryas Impact Event',
    sourceType: 'Academic Paper',
    author: 'Mark Boslough, Ken Nicoll, Vance Holliday, et al.',
    publicationYear: 2012,
    credibilityScore: 0.88,
    notes: 'Compilation of skeptical analyses by geologists who failed to replicate the original impact markers.',
    nodeIds: ['younger-dryas-impact'],
    linkType: 'contradicts',
  },
  {
    slug: 'moore-2017-platinum',
    title: 'Widespread platinum anomaly documented at the Younger Dryas onset in North American sedimentary sequences',
    sourceType: 'Academic Paper',
    author: 'Christopher R. Moore, Mark J. Brooks, Albert C. Goodyear, et al.',
    publicationYear: 2017,
    journal: 'Scientific Reports',
    url: 'https://doi.org/10.1038/s41598-017-04430-4',
    credibilityScore: 0.82,
    notes: 'Documents platinum anomaly at multiple NA sites; the most replicated finding from the impact hypothesis.',
    nodeIds: ['younger-dryas-impact'],
    linkType: 'supports',
  },

  // ── SILK ROAD ─────────────────────────────────────────────────────────────

  {
    slug: 'frankopan-2015-silk-roads',
    title: 'The Silk Roads: A New History',
    sourceType: 'Book',
    author: 'Peter Frankopan',
    publicationYear: 2015,
    publisher: 'Bloomsbury',
    credibilityScore: 0.90,
    notes: 'Revisionist world history placing the Silk Road at the centre of global civilisational development.',
    nodeIds: ['silk-road'],
    linkType: 'supports',
  },
  {
    slug: 'hansen-2012-silk-road',
    title: 'The Silk Road: A New History',
    sourceType: 'Book',
    author: 'Valerie Hansen',
    publicationYear: 2012,
    publisher: 'Oxford University Press',
    credibilityScore: 0.92,
    notes: 'Scholarly history drawing on archaeological evidence and primary sources from Dunhuang and Turfan.',
    nodeIds: ['silk-road'],
    linkType: 'supports',
  },
  {
    slug: 'liu-2010-silk-road-world',
    title: 'The Silk Road in World History',
    sourceType: 'Book',
    author: 'Xinru Liu',
    publicationYear: 2010,
    publisher: 'Oxford University Press',
    credibilityScore: 0.90,
    notes: 'Accessible scholarly synthesis of Silk Road as vehicle for technological and religious diffusion.',
    nodeIds: ['silk-road', 'sumerian-civilization'],
    linkType: 'supports',
  },

  // ── GIANTS IN ANCIENT TEXTS ───────────────────────────────────────────────

  {
    slug: 'west-1997-east-face-helicon',
    title: 'The East Face of Helicon: West Asiatic Elements in Greek Poetry and Myth',
    sourceType: 'Book',
    author: 'M.L. West',
    publicationYear: 1997,
    publisher: 'Oxford University Press',
    credibilityScore: 0.92,
    notes: 'Documents connections between Greek Titan/Giant traditions and ancient Near Eastern parallels.',
    nodeIds: ['giants-ancient-texts', 'comparative-mythology'],
    linkType: 'references',
  },
  {
    slug: 'day-2000-yahweh-canaanite',
    title: 'Yahweh and the Gods and Goddesses of Canaan',
    sourceType: 'Book',
    author: 'John Day',
    publicationYear: 2000,
    publisher: 'Sheffield Academic Press',
    credibilityScore: 0.88,
    notes: 'Scholarly treatment of Rephaim and Anakim traditions in Canaanite religion.',
    nodeIds: ['giants-ancient-texts', 'nephilim'],
    linkType: 'references',
  },

  // ── DRAGON TRADITIONS ─────────────────────────────────────────────────────

  {
    slug: 'jones-2000-instinct-dragons',
    title: 'An Instinct for Dragons',
    sourceType: 'Book',
    author: 'David E. Jones',
    publicationYear: 2000,
    publisher: 'Routledge',
    credibilityScore: 0.82,
    notes: 'Evolutionary psychology hypothesis: dragons as composite predator archetype.',
    nodeIds: ['dragon-traditions'],
    linkType: 'supports',
  },
  {
    slug: 'watkins-1995-kill-dragon',
    title: 'How to Kill a Dragon: Aspects of Indo-European Poetics',
    sourceType: 'Book',
    author: 'Calvert Watkins',
    publicationYear: 1995,
    publisher: 'Oxford University Press',
    credibilityScore: 0.90,
    notes: 'Linguistic and poetic analysis of the dragon-slaying formula across Indo-European traditions.',
    nodeIds: ['dragon-traditions', 'comparative-mythology'],
    linkType: 'supports',
  },
  {
    slug: 'visser-1913-dragon-china-japan',
    title: 'The Dragon in China and Japan',
    sourceType: 'Folklore Collection',
    author: 'Marinus Willem de Visser',
    publicationYear: 1913,
    credibilityScore: 0.78,
    notes: 'Classic scholarly study of East Asian dragon traditions; still widely cited.',
    nodeIds: ['dragon-traditions'],
    linkType: 'references',
  },
];

// ---------------------------------------------------------------------------
// Main seed function
// ---------------------------------------------------------------------------

async function main() {
  console.log('🌱 Starting source population seed...\n');

  let sourcesCreated = 0;
  let linksCreated = 0;
  let sourcesFailed = 0;

  // Use slug-prefixed doi as stable unique key for sources without a real DOI
  const stableDoi = (src: SeedSource) => src.doi ?? `seed:${src.slug}`;

  await Promise.all(SOURCES.map(async (src) => {
    try {
      const created = await prisma.source.upsert({
        where: { doi: stableDoi(src) },
        create: {
          title: src.title,
          sourceType: src.sourceType,
          author: src.author,
          publicationYear: src.publicationYear,
          publisher: src.publisher,
          journal: src.journal,
          url: src.url,
          doi: stableDoi(src),
          notes: `[seed:${src.slug}] ${src.notes ?? ''}`.trim(),
          credibilityScore: src.credibilityScore,
          status: 'approved',
          reviewedAt: new Date(),
          language: 'en',
        },
        update: {
          credibilityScore: src.credibilityScore,
          notes: `[seed:${src.slug}] ${src.notes ?? ''}`.trim(),
        },
      });

      sourcesCreated++;

      await Promise.all(src.nodeIds.map(async (nodeId) => {
        try {
          await prisma.sourceLink.upsert({
            where: {
              sourceId_targetType_targetId_claimIndex: {
                sourceId: created.id,
                targetType: 'node',
                targetId: nodeId,
                claimIndex: null as unknown as number,
              },
            },
            create: {
              sourceId: created.id,
              targetType: 'node',
              targetId: nodeId,
              linkType: src.linkType ?? 'references',
            },
            update: {
              linkType: src.linkType ?? 'references',
            },
          });
          linksCreated++;
        } catch {
          // Unique constraint violation — link already exists
        }
      }));

      process.stdout.write(`  ✓ ${src.slug}\n`);
    } catch (err) {
      console.error(`  ✗ Failed: ${src.slug} — ${(err as Error).message}`);
      sourcesFailed++;
    }
  }));

  console.log(`\n📊 Seed complete:`);
  console.log(`   Sources created/updated: ${sourcesCreated}`);
  console.log(`   Source links created:    ${linksCreated}`);
  console.log(`   Failures:                ${sourcesFailed}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
